import { BibleBookSearch } from "@/components/bible-book-search";

import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { getBibleReaderState } from "@/lib/bible";
import { buildBibleHref, buildBibleReferenceHref, buildCompanionHref } from "@/lib/navigation";
import { buildPageMetadata } from "@/lib/page-metadata";
import { resolveLocale } from "@/lib/server-locale";


type Props = {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ book?: string; chapter?: string; highlight?: string; from?: string }>;
};

type HighlightRange = {
  startVerse: number;
  endVerse: number;
};

const COPY = {
  en: {
    title: "Full Bible reader",
    subtitle: "Read every book and chapter without preview trimming. Choose a book, then move through the complete chapter text.",
    description: "Browse the full Bible text by book and chapter with Korean and English locale support.",
    testament: { old: "Old Testament", new: "New Testament" },
    books: "Books",
    chapters: "Chapters",
    chapter: "Chapter",
    current: "Current reading",
    previous: "Previous",
    next: "Next",
    verseLink: "Highlight this verse",
    startReflection: "Start a reflection from this chapter",
    sourceNote: "English text uses the public-domain World English Bible. Korean text uses Open Bibles kor-korean.osis.xml (“Korean Bible”), not NKRV/개역개정, and is not generated by AI.",
    searchPlaceholder: "Search books…",

  },
  ko: {
    title: "성경 전체 읽기",
    subtitle: "미리보기로 줄이지 않고 66권 전체 본문을 책과 장별로 읽을 수 있습니다. 책을 고르고 장을 넘기면 해당 장의 모든 절이 그대로 표시됩니다.",
    description: "성경 66권 전체 본문을 책과 장별로 읽는 페이지입니다. 한국어와 영어 본문을 지원합니다.",
    testament: { old: "구약", new: "신약" },
    books: "성경 66권",
    chapters: "장 선택",
    chapter: "장",
    current: "현재 읽는 본문",
    previous: "이전",
    next: "다음",
    verseLink: "이 절 강조하기",
    startReflection: "이 장으로 묵상 시작",
    sourceNote: "한국어 본문은 Open Bibles의 kor-korean.osis.xml 기반 “Korean Bible” 코퍼스입니다. 개역개정/NKRV가 아니며, AI가 즉석 번역하거나 생성하지 않습니다.",
    searchPlaceholder: "책 이름 검색…",
  },
} as const;

function parseChapter(value?: string) {
  if (!value) return undefined;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function parseHighlight(value?: string): HighlightRange | undefined {
  const normalized = value?.trim();
  if (!normalized) {
    return undefined;
  }

  const match = normalized.match(/^(\d+)(?:-(\d+))?$/);
  if (!match) {
    return undefined;
  }

  const startVerse = Number(match[1]);
  const endVerse = Number(match[2] ?? match[1]);
  if (!Number.isInteger(startVerse) || !Number.isInteger(endVerse) || startVerse < 1 || endVerse < startVerse) {
    return undefined;
  }

  return { startVerse, endVerse };
}

function parseSourceTag(value?: string) {
  const normalized = value?.trim().toLowerCase();
  if (!normalized || !/^[a-z0-9-]{1,32}$/.test(normalized)) {
    return undefined;
  }

  return normalized;
}

function verseIsHighlighted(highlight: HighlightRange | undefined, verseNumber: number) {
  return Boolean(highlight && verseNumber >= highlight.startVerse && verseNumber <= highlight.endVerse);
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale: requestedLocale } = await params;
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];

  return buildPageMetadata(locale, copy.title, copy.description, "/bible");
}

export default async function BiblePage({ params, searchParams }: Props) {
  const [{ locale: requestedLocale }, { book, chapter, highlight, from }] = await Promise.all([params, searchParams]);
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];
  const sourceTag = parseSourceTag(from);
  const requestedHighlight = parseHighlight(highlight);
  const reader = await getBibleReaderState({ code: book, chapter: parseChapter(chapter), locale });

  if (!reader) {
    notFound();
  }

  const highlightedRange =
    requestedHighlight && reader.verses.some((verse) => verseIsHighlighted(requestedHighlight, verse.verse))
      ? requestedHighlight
      : undefined;

  const renderChapterLinks = (className: string) => (
    <div className={className}>
      {reader.chapters.map((chapterNumber) => {
        const selected = chapterNumber === reader.selectedChapter;
        return (
          <Link
            key={chapterNumber}
            href={buildBibleHref({ book: reader.selectedBook.code, chapter: chapterNumber, locale, from: sourceTag })}
            className={`min-h-[44px] min-w-11 rounded-lg px-3 py-2 text-center text-sm font-semibold transition ${
              selected
                ? "bg-[var(--gold)] text-[var(--canvas)]"
                : "border border-[var(--hairline)] bg-[var(--surface-2)] text-[var(--ink)] hover:border-[var(--gold)]/30 hover:text-[var(--gold)]"
            }`}
          >
            {chapterNumber}
          </Link>
        );
      })}
    </div>
  );

  const previousBook = reader.previous ? reader.books.find((item) => item.code === reader.previous?.code) : null;
  const nextBook = reader.next ? reader.books.find((item) => item.code === reader.next?.code) : null;

  const chapterPrompt =
    locale === "ko"
      ? `${reader.selectedBook.name} ${reader.selectedChapter}장을 문맥과 연결 본문으로 공부하고 싶어요.`
      : `Help me study ${reader.selectedBook.name} ${reader.selectedChapter} with context and linked passages.`;

  return (
    <main className="page-shell-wide">

      <section className="mt-8 glass rounded-2xl p-5 sm:p-6 lg:p-8">
        <div className="section-title text-base">{copy.current}</div>
        <div className="mt-5 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <h1 className="text-4xl font-bold leading-tight tracking-tight text-[var(--ink)] lg:text-6xl">{copy.title}</h1>
            <p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--muted)]">{copy.subtitle}</p>
          </div>
          <div className="rounded-[24px] border border-[var(--gold)]/20 bg-[var(--gold)]/[0.08] px-5 py-4 text-sm leading-6 text-[var(--muted)] lg:max-w-xs">
            {copy.sourceNote}
          </div>
        </div>
      </section>

      <section className="mt-8 grid gap-8 md:grid-cols-[280px_minmax(0,1fr)] lg:grid-cols-[320px_minmax(0,1fr)] md:items-start">
        <aside className="glass scrollbar-thin rounded-2xl p-5 sm:p-6 lg:sticky lg:top-[calc(var(--nav-height)+1.5rem)] lg:max-h-[calc(100vh-5rem)] lg:overflow-y-auto">
          <div className="section-title text-base">{copy.books}</div>
          <div className="mt-4">
            <BibleBookSearch
              books={reader.books.map((item) => ({ code: item.code, name: item.name, testament: item.testament }))}
              selectedCode={reader.selectedBook.code}

              locale={locale}
              copy={{
                old: copy.testament.old,
                new: copy.testament.new,
                searchPlaceholder: copy.searchPlaceholder,
                books: copy.books,
              }}
            />
          </div>
        </aside>

        <div className="space-y-8">
          <section className="glass rounded-2xl p-5 sm:p-6 lg:p-8">
            <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <div className="section-title text-base">{copy.current}</div>
                <h2 className="mt-3 text-3xl font-bold tracking-tight text-[var(--ink)] lg:text-5xl">
                  {reader.selectedBook.name} {reader.selectedChapter}{copy.chapter}
                </h2>
              </div>
              <Link
                href={buildCompanionHref({ prompt: chapterPrompt, locale })}
                className="inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--gold)] px-5 py-3 text-sm font-semibold text-[var(--canvas)] transition hover:bg-[var(--gold-hover)]"
              >
                <Sparkles className="h-4 w-4" />
                {copy.startReflection}
              </Link>
            </div>

            <div className="mt-7 rounded-xl border border-[var(--hairline)] bg-[var(--surface-2)] p-5 sm:p-6 lg:p-8">
              <div className="mb-4 flex items-center gap-2 text-sm font-semibold text-[var(--muted)]">
                <BookOpen className="h-4 w-4 text-[var(--gold)]" />
                {copy.chapters}
              </div>
              <details className="md:hidden">
                <summary className="cursor-pointer rounded-lg border border-[var(--hairline)] bg-[var(--surface-2)] px-4 py-3 text-sm font-semibold text-[var(--ink)]">
                  {copy.chapters} · {reader.selectedChapter}{copy.chapter}
                </summary>
                <div className="mt-4">{renderChapterLinks("flex flex-wrap gap-2")}</div>
              </details>
              {renderChapterLinks("hidden flex-wrap gap-2 md:flex")}
            </div>
          </section>

          <article className="rounded-2xl border border-[var(--gold)]/20 bg-[var(--gold)]/[0.07] p-5 sm:p-6 lg:p-8">
            <div className="verse-container reading-column space-y-4 text-[var(--ink)]">
              {reader.verses.map((verse) => {
                const highlighted = verseIsHighlighted(highlightedRange, verse.verse);
                return (
                  <p
                    key={`${verse.code}-${verse.chapter}-${verse.verse}`}
                    className={`grid grid-cols-[3rem_minmax(0,1fr)] gap-3 rounded-xl ${
                      highlighted ? "border border-[var(--gold)]/30 bg-[var(--gold)]/[0.16] px-3 py-3" : ""
                    }`}
                  >
                    <Link
                      href={buildBibleReferenceHref(
                        { code: verse.code, chapter: verse.chapter, startVerse: verse.verse, endVerse: verse.verse },
                        { locale, from: sourceTag },
                      )}
                      className={`inline-flex h-[44px] w-[44px] items-center justify-center rounded-lg text-base font-bold leading-8 transition ${
                        highlighted
                          ? "bg-[var(--gold)] text-[var(--canvas)]"
                          : "text-[var(--gold)] hover:bg-[var(--gold)]/10 hover:text-[var(--ink)]"
                      }`}
                      aria-label={`${copy.verseLink}: ${reader.selectedBook.name} ${verse.chapter}:${verse.verse}`}
                    >
                      {verse.verse}
                    </Link>
                    <span className={highlighted ? "text-[var(--ink)]" : undefined}>{verse.text}</span>
                  </p>
                );
              })}
            </div>
          </article>

          <nav className="grid gap-4 sm:grid-cols-2" aria-label="Chapter navigation">
            {reader.previous && previousBook ? (
              <Link
                href={buildBibleHref({ book: reader.previous.code, chapter: reader.previous.chapter, locale, from: sourceTag })}
                className="glass rounded-2xl p-5 transition hover:border-[var(--gold)]/30"
              >
                <span className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted)]">
                  <ArrowLeft className="h-4 w-4" />
                  {copy.previous}
                </span>
                <span className="mt-2 block text-lg font-bold text-[var(--ink)]">
                  {previousBook.name} {reader.previous.chapter}{copy.chapter}
                </span>
              </Link>
            ) : null}
            {reader.next && nextBook ? (
              <Link
                href={buildBibleHref({ book: reader.next.code, chapter: reader.next.chapter, locale, from: sourceTag })}
                className={`glass rounded-2xl p-5 text-right transition hover:border-[var(--gold)]/30 ${!reader.previous || !previousBook ? "sm:col-span-2" : ""}`}
              >
                <span className="inline-flex items-center justify-end gap-2 text-sm font-semibold text-[var(--muted)]">
                  {copy.next}
                  <ArrowRight className="h-4 w-4" />
                </span>
                <span className="mt-2 block text-lg font-bold text-[var(--ink)]">
                  {nextBook.name} {reader.next.chapter}{copy.chapter}
                </span>
              </Link>
            ) : null}
          </nav>
        </div>
      </section>
    </main>
  );
}
