import { BibleBookSearch } from "@/components/bible-book-search";

import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { getBibleReaderState } from "@/lib/bible";
import { buildBibleHref, buildBibleReferenceHref, buildCompanionHref } from "@/lib/navigation";
import { buildPageMetadata } from "@/lib/page-metadata";
import { resolveLocale } from "@/lib/server-locale";
import { getPassageCrossReferences } from "@/lib/knowledge";


type Props = {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ book?: string; chapter?: string; highlight?: string; from?: string }>;
};

type HighlightRange = {
  startVerse: number;
  endVerse: number;
};

const COPY = {
  en: {
    title: "Full Bible reader",
    subtitle: "Read every book and chapter without preview trimming. Choose a book, then move through the complete chapter text.",
    description: "Browse the full Bible text by book and chapter with Korean and English locale support.",
    testament: { old: "Old Testament", new: "New Testament" },
    books: "Books",
    chapters: "Chapters",
    chapter: "Chapter",
    current: "Current reading",
    previous: "Previous",
    next: "Next",
    verseLink: "Highlight this verse",
    startReflection: "Start a reflection from this chapter",
    sourceNote: "English text uses the public-domain World English Bible. Korean text uses Open Bibles kor-korean.osis.xml (“Korean Bible”), not NKRV/개역개정, and is not generated by AI.",
    searchPlaceholder: "Search books…",
    supportTitle: "Supporting passages",
    supportBody: "Open these linked texts to cross-check and deepen the highlighted passage.",
    supportEmpty: "No direct supporting links were found for this highlighted range yet.",
    openSupport: "Open supporting passage",
  },
  ko: {
    title: "성경 전체 읽기",
    subtitle: "미리보기로 줄이지 않고 66권 전체 본문을 책과 장별로 읽을 수 있습니다. 책을 고르고 장을 넘기면 해당 장의 모든 절이 그대로 표시됩니다.",
    description: "성경 66권 전체 본문을 책과 장별로 읽는 페이지입니다. 한국어와 영어 본문을 지원합니다.",
    testament: { old: "구약", new: "신약" },
    books: "성경 66권",
    chapters: "장 선택",
    chapter: "장",
    current: "현재 읽는 본문",
    previous: "이전",
    next: "다음",
    verseLink: "이 절 강조하기",
    startReflection: "이 장으로 묵상 시작",
    sourceNote: "한국어 본문은 Open Bibles의 kor-korean.osis.xml 기반 “Korean Bible” 코퍼스입니다. 개역개정/NKRV가 아니며, AI가 즉석 번역하거나 생성하지 않습니다.",
    searchPlaceholder: "책 이름 검색…",
    supportTitle: "이 본문을 뒷받침하는 성구",
    supportBody: "강조된 본문과 직접 연결되는 성구들입니다. 상담 답변에서 제시한 본문을 더 넓게 확인할 때 함께 열어 보세요.",
    supportEmpty: "아직 이 강조 범위를 직접 뒷받침하는 연결 성구가 충분하지 않습니다.",
    openSupport: "뒷받침 성구 열기",
  },
} as const;

function parseChapter(value?: string) {
  if (!value) return undefined;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function parseHighlight(value?: string): HighlightRange | undefined {
  const normalized = value?.trim();
  if (!normalized) {
    return undefined;
  }

  const match = normalized.match(/^(\d+)(?:-(\d+))?$/);
  if (!match) {
    return undefined;
  }

  const startVerse = Number(match[1]);
  const endVerse = Number(match[2] ?? match[1]);
  if (!Number.isInteger(startVerse) || !Number.isInteger(endVerse) || startVerse < 1 || endVerse < startVerse) {
    return undefined;
  }

  return { startVerse, endVerse };
}

function parseSourceTag(value?: string) {
  const normalized = value?.trim().toLowerCase();
  if (!normalized || !/^[a-z0-9-]{1,32}$/.test(normalized)) {
    return undefined;
  }

  return normalized;
}

function verseIsHighlighted(highlight: HighlightRange | undefined, verseNumber: number) {
  return Boolean(highlight && verseNumber >= highlight.startVerse && verseNumber <= highlight.endVerse);
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale: requestedLocale } = await params;
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];

  return buildPageMetadata(locale, copy.title, copy.description, "/bible");
}

export default async function BiblePage({ params, searchParams }: Props) {
  const [{ locale: requestedLocale }, { book, chapter, highlight, from }] = await Promise.all([params, searchParams]);
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];
  const sourceTag = parseSourceTag(from);
  const requestedHighlight = parseHighlight(highlight);
  const reader = await getBibleReaderState({ code: book, chapter: parseChapter(chapter), locale });

  if (!reader) {
    notFound();
  }

  const highlightedRange =
    requestedHighlight && reader.verses.some((verse) => verseIsHighlighted(requestedHighlight, verse.verse))
      ? requestedHighlight
      : undefined;
  const supportReference = highlightedRange
    ? {
        code: reader.selectedBook.code,
        chapter: reader.selectedChapter,
        startVerse: highlightedRange.startVerse,
        endVerse: highlightedRange.endVerse,
      }
    : null;
  const supportSuggestions = supportReference ? await getPassageCrossReferences(supportReference, 5, locale) : [];

  const renderChapterLinks = (className: string) => (
    <div className={className}>
      {reader.chapters.map((chapterNumber) => {
        const selected = chapterNumber === reader.selectedChapter;
        return (
          <Link
            key={chapterNumber}
            href={buildBibleHref({ book: reader.selectedBook.code, chapter: chapterNumber, locale, from: sourceTag })}
            className={`min-h-[44px] min-w-11 rounded-lg px-3 py-2 text-center text-sm font-semibold transition ${
              selected
                ? "bg-[var(--gold)] text-[var(--canvas)]"
                : "border border-[var(--hairline)] bg-[var(--surface-2)] text-[var(--ink)] hover:border-[var(--gold)]/30 hover:text-[var(--gold)]"
            }`}
          >
            {chapterNumber}
          </Link>
        );
      })}
    </div>
  );

  const previousBook = reader.previous ? reader.books.find((item) => item.code === reader.previous?.code) : null;
  const nextBook = reader.next ? reader.books.find((item) => item.code === reader.next?.code) : null;

  const chapterPrompt =
    locale === "ko"
      ? `${reader.selectedBook.name} ${reader.selectedChapter}장을 문맥과 연결 본문으로 공부하고 싶어요.`
      : `Help me study ${reader.selectedBook.name} ${reader.selectedChapter} with context and linked passages.`;

  return (
    <main className="page-shell-wide">
      <section className="grid gap-4 lg:grid-cols-[320px_minmax(0,1fr)] lg:items-start">
        <aside className="hidden lg:sticky lg:top-[calc(var(--nav-height)+1rem)] lg:block lg:max-h-[calc(100dvh-var(--nav-height)-2rem)] lg:overflow-hidden">
          <div className="glass flex max-h-[inherit] flex-col rounded-2xl p-5">
            <div>
              <div className="section-title text-base">{copy.books}</div>
              <p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy.sourceNote}</p>
            </div>
            <div className="mt-4 min-h-0 overflow-y-auto pr-1 scrollbar-thin">
              <BibleBookSearch
                books={reader.books.map((item) => ({ code: item.code, name: item.name, testament: item.testament }))}
                selectedCode={reader.selectedBook.code}
                locale={locale}
                copy={{
                  old: copy.testament.old,
                  new: copy.testament.new,
                  searchPlaceholder: copy.searchPlaceholder,
                  books: copy.books,
                }}
              />
            </div>
          </div>
        </aside>

        <div className="min-w-0">
          <section className="glass rounded-[1.35rem] p-3 shadow-[var(--shadow-soft)] sm:rounded-2xl sm:p-4 lg:rounded-[1.75rem]">
            <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
              <div className="min-w-0">
                <div className="section-title text-xs sm:text-sm">{copy.current}</div>
                <h1 className="mt-1 truncate text-[1.75rem] font-[850] leading-none tracking-[-0.045em] text-[var(--ink)] sm:text-3xl lg:text-4xl">
                  {reader.selectedBook.name} {reader.selectedChapter}{copy.chapter}
                </h1>
              </div>

              <div className="grid grid-cols-[minmax(2.75rem,1fr)_auto_minmax(2.75rem,1fr)] items-stretch gap-2 lg:w-auto">
                {reader.previous && previousBook ? (
                  <Link
                    href={buildBibleHref({ book: reader.previous.code, chapter: reader.previous.chapter, locale, from: sourceTag })}
                    className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-2xl border border-[var(--hairline)] bg-[var(--surface-2)] px-3 text-sm font-bold text-[var(--ink)] transition hover:border-[var(--gold)]/40 hover:bg-[var(--gold-soft)] hover:text-[var(--gold)]"
                    aria-label={`${copy.previous}: ${previousBook.name} ${reader.previous.chapter}${copy.chapter}`}
                  >
                    <ArrowLeft className="h-4 w-4" />
                    <span className="hidden sm:inline">{copy.previous}</span>
                  </Link>
                ) : (
                  <span aria-hidden="true" />
                )}

                <details className="group relative">
                  <summary className="flex min-h-[44px] cursor-pointer list-none items-center justify-center rounded-2xl bg-[var(--gold)] px-5 text-sm font-bold text-[var(--canvas)] shadow-sm transition hover:bg-[var(--gold-hover)] [&::-webkit-details-marker]:hidden">
                    {copy.chapters}
                  </summary>
                  <div className="absolute right-1/2 z-30 mt-3 max-h-[min(72dvh,34rem)] w-[min(calc(100vw-1.75rem),42rem)] translate-x-1/2 overflow-y-auto rounded-[1.5rem] border border-[var(--hairline)] bg-[var(--surface-1)] p-4 shadow-[var(--shadow-lifted)] scrollbar-thin sm:right-0 sm:translate-x-0">
                    <div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_minmax(13rem,16rem)]">
                      <div className="lg:hidden">
                        <div className="mb-3 text-xs font-bold uppercase tracking-[0.12em] text-[var(--gold)]">{copy.books}</div>
                        <BibleBookSearch
                          books={reader.books.map((item) => ({ code: item.code, name: item.name, testament: item.testament }))}
                          selectedCode={reader.selectedBook.code}
                          locale={locale}
                          copy={{
                            old: copy.testament.old,
                            new: copy.testament.new,
                            searchPlaceholder: copy.searchPlaceholder,
                            books: copy.books,
                          }}
                        />
                      </div>
                      <div className="order-first md:order-none md:col-start-2 lg:col-start-1">
                        <div className="mb-3 flex items-center gap-2 text-sm font-bold text-[var(--muted)]">
                          <BookOpen className="h-4 w-4 text-[var(--gold)]" />
                          {reader.selectedBook.name} · {copy.chapters}
                        </div>
                        {renderChapterLinks("grid grid-cols-5 gap-2 sm:grid-cols-6")}
                      </div>
                    </div>
                  </div>
                </details>

                {reader.next && nextBook ? (
                  <Link
                    href={buildBibleHref({ book: reader.next.code, chapter: reader.next.chapter, locale, from: sourceTag })}
                    className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-2xl border border-[var(--hairline)] bg-[var(--surface-2)] px-3 text-sm font-bold text-[var(--ink)] transition hover:border-[var(--gold)]/40 hover:bg-[var(--gold-soft)] hover:text-[var(--gold)]"
                    aria-label={`${copy.next}: ${nextBook.name} ${reader.next.chapter}${copy.chapter}`}
                  >
                    <span className="hidden sm:inline">{copy.next}</span>
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                ) : (
                  <span aria-hidden="true" />
                )}
              </div>
            </div>


          </section>

          <article className="mt-4 rounded-[1.6rem] border border-[var(--gold)]/20 bg-[var(--gold)]/[0.07] p-4 shadow-[var(--shadow-soft)] sm:rounded-[2rem] sm:p-6 lg:p-8">
            <div className="verse-container reading-column space-y-3 text-[var(--ink)] sm:space-y-4">
              {reader.verses.map((verse) => {
                const highlighted = verseIsHighlighted(highlightedRange, verse.verse);
                return (
                  <p
                    key={`${verse.code}-${verse.chapter}-${verse.verse}`}
                    className={`grid grid-cols-[2.75rem_minmax(0,1fr)] gap-3 rounded-xl text-lg leading-8 sm:grid-cols-[3rem_minmax(0,1fr)] ${
                      highlighted ? "border border-[var(--gold)]/30 bg-[var(--gold)]/[0.16] px-3 py-3" : ""
                    }`}
                  >
                    <Link
                      href={buildBibleReferenceHref(
                        { code: verse.code, chapter: verse.chapter, startVerse: verse.verse, endVerse: verse.verse },
                        { locale, from: sourceTag },
                      )}
                      className={`inline-flex h-[44px] w-[44px] items-center justify-center rounded-lg text-base font-bold leading-8 transition ${
                        highlighted
                          ? "bg-[var(--gold)] text-[var(--canvas)]"
                          : "text-[var(--gold)] hover:bg-[var(--gold)]/10 hover:text-[var(--ink)]"
                      }`}
                      aria-label={`${copy.verseLink}: ${reader.selectedBook.name} ${verse.chapter}:${verse.verse}`}
                    >
                      {verse.verse}
                    </Link>
                    <span className={highlighted ? "text-[var(--ink)]" : undefined}>{verse.text}</span>
                  </p>
                );
              })}
            </div>
          </article>

          {highlightedRange ? (
            <section className="mt-4 rounded-2xl border border-[var(--hairline)] bg-[var(--surface-2)] p-4 sm:p-5">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
                <div>
                  <div className="section-title text-sm">{copy.supportTitle}</div>
                  <p className="mt-2 text-sm leading-6 text-[var(--muted)]">{copy.supportBody}</p>
                </div>
                <div className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--gold)]">
                  {reader.selectedBook.name} {reader.selectedChapter}:{highlightedRange.startVerse}
                  {highlightedRange.startVerse === highlightedRange.endVerse ? "" : `-${highlightedRange.endVerse}`}
                </div>
              </div>

              {supportSuggestions.length ? (
                <div className="mt-4 grid gap-3 md:grid-cols-2">
                  {supportSuggestions.map((suggestion) => (
                    <Link
                      key={`${suggestion.target.code}-${suggestion.target.chapter}-${suggestion.target.startVerse}-${suggestion.target.endVerse}`}
                      href={buildBibleReferenceHref(suggestion.target, { locale, from: sourceTag })}
                      className="rounded-2xl border border-[var(--hairline)] bg-[var(--surface)] p-4 transition hover:border-[var(--gold)]/40 hover:bg-[var(--gold)]/10"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <div className="text-sm font-bold text-[var(--ink)]">{suggestion.displayReference}</div>
                          <div className="mt-1 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--gold)]">
                            {suggestion.supportLabel}
                          </div>
                        </div>
                        <ArrowRight className="mt-0.5 h-4 w-4 shrink-0 text-[var(--gold)]" aria-hidden="true" />
                      </div>
                      {suggestion.supportLine ? (
                        <p className="mt-3 text-xs leading-5 text-[var(--muted)]">{suggestion.supportLine}</p>
                      ) : null}
                      <p className="mt-3 text-sm leading-6 text-[var(--muted)]">{suggestion.excerpt}</p>
                      <div className="mt-3 text-sm font-semibold text-[var(--gold)]">{copy.openSupport}</div>
                    </Link>
                  ))}
                </div>
              ) : (
                <p className="mt-4 text-sm leading-6 text-[var(--muted)]">{copy.supportEmpty}</p>
              )}
            </section>
          ) : null}

          <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]">
            <div className="rounded-2xl border border-[var(--hairline)] bg-[var(--surface-2)] px-4 py-3 text-sm leading-6 text-[var(--muted)] lg:hidden">
              {copy.sourceNote}
            </div>
            <Link
              href={buildCompanionHref({ prompt: chapterPrompt, locale })}
              className="inline-flex min-h-[48px] items-center justify-center gap-2 rounded-xl bg-[var(--gold)] px-5 py-3 text-sm font-semibold text-[var(--canvas)] transition hover:bg-[var(--gold-hover)]"
            >
              <Sparkles className="h-4 w-4" />
              {copy.startReflection}
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
