import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Sparkles } from "lucide-react";
import { notFound } from "next/navigation";
import { getBibleReaderState } from "@/lib/bible";
import { type AppLocale } from "@/lib/content";
import { buildBibleHref, buildCompanionHref, buildPassageHref } from "@/lib/navigation";
import { buildPageMetadata } from "@/lib/page-metadata";
import { resolveLocale } from "@/lib/server-locale";
import { SecondaryNav } from "@/components/secondary-nav";

type Props = {
  params: Promise<{ locale: string }>;
  searchParams: Promise<{ book?: string; chapter?: string }>;
};

const COPY = {
  en: {
    title: "Full Bible reader",
    subtitle: "Read every book and chapter without preview trimming. Choose a book, then move through the complete chapter text.",
    description: "Browse the full Bible text by book and chapter with Korean and English locale support.",
    testament: { old: "Old Testament", new: "New Testament" },
    books: "Books",
    chapters: "Chapters",
    chapter: "Chapter",
    current: "Current reading",
    previous: "Previous",
    next: "Next",
    verseLink: "Open this verse",
    startReflection: "Start a reflection from this chapter",
    sourceNote: "Text source is loaded from the local public-domain Bible corpus, not generated by AI.",
  },
  ko: {
    title: "성경 전체 읽기",
    subtitle: "미리보기로 줄이지 않고 66권 전체 본문을 책과 장별로 읽을 수 있습니다. 책을 고르고 장을 넘기면 해당 장의 모든 절이 그대로 표시됩니다.",
    description: "성경 66권 전체 본문을 책과 장별로 읽는 페이지입니다. 한국어와 영어 본문을 지원합니다.",
    testament: { old: "구약", new: "신약" },
    books: "성경 66권",
    chapters: "장 선택",
    chapter: "장",
    current: "현재 읽는 본문",
    previous: "이전",
    next: "다음",
    verseLink: "이 절만 열기",
    startReflection: "이 장으로 묵상 시작",
    sourceNote: "본문은 로컬의 퍼블릭 도메인 성경 코퍼스에서 불러오며, AI가 즉석 번역하거나 생성하지 않습니다.",
  },
} as const;

function parseChapter(value?: string) {
  if (!value) return undefined;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function testamentKey(testament: string, locale: AppLocale) {
  if (locale === "ko") {
    return testament.includes("신약") ? "new" : "old";
  }

  return testament.toLowerCase().includes("new") ? "new" : "old";
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale: requestedLocale } = await params;
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];

  return buildPageMetadata(locale, copy.title, copy.description, "/bible");
}

export default async function BiblePage({ params, searchParams }: Props) {
  const [{ locale: requestedLocale }, { book, chapter }] = await Promise.all([params, searchParams]);
  const locale = await resolveLocale(requestedLocale);
  const copy = COPY[locale];
  const reader = await getBibleReaderState({ code: book, chapter: parseChapter(chapter), locale });

  if (!reader) {
    notFound();
  }

  const groupedBooks = reader.books.reduce<Record<"old" | "new", typeof reader.books>>(
    (groups, currentBook) => {
      groups[testamentKey(currentBook.testament, locale)].push(currentBook);
      return groups;
    },
    { old: [], new: [] },
  );

  const previousBook = reader.previous ? reader.books.find((item) => item.code === reader.previous?.code) : null;
  const nextBook = reader.next ? reader.books.find((item) => item.code === reader.next?.code) : null;
  const chapterPrompt =
    locale === "ko"
      ? `${reader.selectedBook.name} ${reader.selectedChapter}장을 문맥과 연결 본문으로 공부하고 싶어요.`
      : `Help me study ${reader.selectedBook.name} ${reader.selectedChapter} with context and linked passages.`;
  const renderBookGroups = (gridClassName: string) => (
    <div className="space-y-6">
      {(["old", "new"] as const).map((group) => (
        <div key={group}>
          <div className="mb-3 text-sm font-semibold text-[var(--gold)]">{copy.testament[group]}</div>
          <div className={gridClassName}>
            {groupedBooks[group].map((item) => {
              const selected = item.code === reader.selectedBook.code;
              return (
                <Link
                  key={item.code}
                  href={buildBibleHref({ book: item.code, chapter: 1, locale })}
                  className={`min-h-[44px] rounded-lg px-3 py-2.5 text-sm font-semibold transition ${
                    selected
                      ? "bg-[var(--gold)] text-[var(--canvas)]"
                      : "border border-[var(--hairline)] bg-[var(--surface-2)] text-[var(--ink)] hover:border-[var(--gold)]/30 hover:text-[var(--gold)]"
                  }`}
                >
                  <span className="block truncate">{item.name}</span>
                  <span className="mt-1 block text-[11px] font-medium opacity-70">{item.code}</span>
                </Link>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
  const renderChapterLinks = (className: string) => (
    <div className={className}>
      {reader.chapters.map((chapterNumber) => {
        const selected = chapterNumber === reader.selectedChapter;
        return (
          <Link
            key={chapterNumber}
            href={buildBibleHref({ book: reader.selectedBook.code, chapter: chapterNumber, locale })}
            className={`min-h-[44px] min-w-11 rounded-lg px-3 py-2 text-center text-sm font-semibold transition ${
              selected
                ? "bg-[var(--gold)] text-[var(--canvas)]"
                : "border border-[var(--hairline)] bg-[var(--surface-2)] text-[var(--ink)] hover:border-[var(--gold)]/30 hover:text-[var(--gold)]"
            }`}
          >
            {chapterNumber}
          </Link>
        );
      })}
    </div>
  );

  return (
    <main className="mx-auto min-h-screen max-w-7xl px-6 py-8 lg:px-8">
      <SecondaryNav locale={locale} active="bible" title={copy.title} />

      <section className="mt-8 glass rounded-2xl p-5 sm:p-6 lg:p-8">
        <div className="section-title text-base">{copy.current}</div>
        <div className="mt-5 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <h1 className="text-4xl font-bold leading-tight tracking-tight text-[var(--ink)] lg:text-6xl">{copy.title}</h1>
            <p className="mt-5 max-w-3xl text-lg leading-8 text-[var(--muted)]">{copy.subtitle}</p>
          </div>
          <div className="rounded-[24px] border border-[var(--gold)]/20 bg-[var(--gold)]/[0.08] px-5 py-4 text-sm leading-6 text-[var(--muted)] lg:max-w-xs">
            {copy.sourceNote}
          </div>
        </div>
      </section>

      <section className="mt-8 grid gap-8 md:grid-cols-[280px_minmax(0,1fr)] lg:grid-cols-[320px_minmax(0,1fr)] md:items-start">
        <aside className="glass scrollbar-thin rounded-2xl p-5 sm:p-6 lg:p-8 lg:sticky lg:top-28 lg:max-h-[calc(100vh-8rem)] lg:overflow-y-auto">
          <details className="lg:hidden">
            <summary className="cursor-pointer rounded-lg border border-[var(--hairline)] bg-[var(--surface-2)] px-4 py-3 text-sm font-semibold text-[var(--ink)]">
              {copy.books} · {reader.selectedBook.name}
            </summary>
            <div className="mt-5">{renderBookGroups("grid grid-cols-2 gap-2 sm:grid-cols-3")}</div>
          </details>
          <div className="hidden lg:block">
            <div className="section-title text-base">{copy.books}</div>
            <div className="mt-5">{renderBookGroups("grid grid-cols-2 gap-2")}</div>
          </div>
        </aside>

        <div className="space-y-8">
          <section className="glass rounded-2xl p-5 sm:p-6 lg:p-8">
            <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <div className="section-title text-base">{copy.current}</div>
                <h2 className="mt-3 text-3xl font-bold tracking-tight text-[var(--ink)] lg:text-5xl">
                  {reader.selectedBook.name} {reader.selectedChapter}{copy.chapter}
                </h2>
              </div>
              <Link
                href={buildCompanionHref({ prompt: chapterPrompt, locale })}
                className="inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--gold)] px-5 py-3 text-sm font-semibold text-[var(--canvas)] transition hover:bg-[var(--gold-hover)]"
              >
                <Sparkles className="h-4 w-4" />
                {copy.startReflection}
              </Link>
            </div>

            <div className="mt-7 rounded-xl border border-[var(--hairline)] bg-[var(--surface-2)] p-5 sm:p-6 lg:p-8">
              <div className="mb-4 flex items-center gap-2 text-sm font-semibold text-[var(--muted)]">
                <BookOpen className="h-4 w-4 text-[var(--gold)]" />
                {copy.chapters}
              </div>
              <details className="lg:hidden">
                <summary className="cursor-pointer rounded-lg border border-[var(--hairline)] bg-[var(--surface-2)] px-4 py-3 text-sm font-semibold text-[var(--ink)]">
                  {copy.chapters} · {reader.selectedChapter}{copy.chapter}
                </summary>
                <div className="mt-4">{renderChapterLinks("flex flex-wrap gap-2")}</div>
              </details>
              {renderChapterLinks("hidden flex-wrap gap-2 lg:flex")}
            </div>
          </section>

          <article className="rounded-2xl border border-[var(--gold)]/20 bg-[var(--gold)]/[0.07] p-5 sm:p-6 lg:p-8">
            <div className="verse-container mx-auto max-w-3xl space-y-4 text-[var(--text)]">
              {reader.verses.map((verse) => (
                <p key={`${verse.code}-${verse.chapter}-${verse.verse}`} className="grid grid-cols-[3rem_minmax(0,1fr)] gap-3">
                  <Link
                    href={buildPassageHref(
                      { code: verse.code, chapter: verse.chapter, startVerse: verse.verse, endVerse: verse.verse },
                      locale,
                    )}
                    className="pt-1 text-base font-bold leading-8 text-[var(--gold)] transition hover:text-[var(--ink)]"
                    aria-label={`${copy.verseLink}: ${reader.selectedBook.name} ${verse.chapter}:${verse.verse}`}
                  >
                    {verse.verse}
                  </Link>
                  <span>{verse.text}</span>
                </p>
              ))}
            </div>
          </article>

          <nav className="grid gap-4 sm:grid-cols-2" aria-label="Chapter navigation">
            {reader.previous && previousBook ? (
              <Link
                href={buildBibleHref({ book: reader.previous.code, chapter: reader.previous.chapter, locale })}
                className="glass rounded-2xl p-5 transition hover:border-[var(--gold)]/30"
              >
                <span className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--muted)]">
                  <ArrowLeft className="h-4 w-4" />
                  {copy.previous}
                </span>
                <span className="mt-2 block text-lg font-bold text-[var(--ink)]">
                  {previousBook.name} {reader.previous.chapter}{copy.chapter}
                </span>
              </Link>
            ) : (
              <div />
            )}
            {reader.next && nextBook ? (
              <Link
                href={buildBibleHref({ book: reader.next.code, chapter: reader.next.chapter, locale })}
                className="glass rounded-2xl p-5 text-right transition hover:border-[var(--gold)]/30"
              >
                <span className="inline-flex items-center justify-end gap-2 text-sm font-semibold text-[var(--muted)]">
                  {copy.next}
                  <ArrowRight className="h-4 w-4" />
                </span>
                <span className="mt-2 block text-lg font-bold text-[var(--ink)]">
                  {nextBook.name} {reader.next.chapter}{copy.chapter}
                </span>
              </Link>
            ) : null}
          </nav>
        </div>
      </section>
    </main>
  );
}
